import Nav from "@/Works/Nav";
import "./globals.css";
import { Montserrat } from "next/font/google";

export const metadata = {
  title: "Estilo",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  weight: ["400", "100", "200", "900", "500", "600", "800", "700"], // Choose the weights you need
  subsets: ["latin"], // Specify the subsets
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Nav />
        <div className="tablet:mt-16 mt-12">{children}</div>
      </body>
    </html>
  );
}
